export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';

export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const GET_CUSTOMERS = 'GET_CUSTOMERS';
export const DELETE_CUSTOMER  = 'DELETE_CUSTOMER';
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER';
export const CUSTOMER_ERROR = 'CUSTOMER_ERROR';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const DELETE_PRODUCT  = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

export const GET_TRANSACTIONS  = 'GET_TRANSACTIONS';
export const TRANSACTION_ERROR  = 'TRANSACTION_ERROR';
export const ADD_TRANSACTION = 'ADD_TRANSACTION';